name: 'Setup Node.js and Dependencies'
description: 'Setup Node.js with version from .nvmrc and install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Read .nvmrc
      id: node-version
      shell: bash
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ steps.node-version.outputs.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci
